Folder Refactor [DO NOT MERGE TILL WINTER BREAK]
cornell-dti/course-plan pull request #232
Opened 2020-12-14 03:32 UTC by hahnbeelee

### Summary
- Added a `containers` folder where the main "pages" lie (Login, 404, Dashboard, Settings (?))
- Organized components into folders
   - All components related to Requirements/SemesterView/BottomBar in one folder
   - Components that are re-used in multiple places are kept at the highest level `Components` folder ( e.g. `Course.vue` and `DropdownArrow.vue`)

### Test Plan
- Make sure `npm run serve` works
- Look through the file structure and see if it makes sense
  - specifically, see if there are some components in sub-folders that should be at the highest level.

2020-12-14 03:40 UTC, hahnbeelee commented on src/components/Navigation.vue
> -<template>
this didn't seem like it was being used anywhere and my GitLens extension was telling me that it was added on `first commit` so I'm assuming this is outdated lol

2020-12-14 15:31 UTC, SamChou19815 approved these changes
Actually looks good to go. git can detect changed files so merge conflicts won't be too bad.

2020-12-14 23:14 UTC, hahnbeelee commented
@willespencer thoughts on just merging this rn?

2020-12-15 03:03 UTC, willespencer requested changes
Thanks for doing this Hahnbee! I'm trusting Sam on this one so I do think we can merge it in, just make sure you mention that this happened in cp-dev after this gets finished. I also have a couple suggested changes haha.

- Can you move the 4 onboarding components and 1 scss file to their own separate folder as well?
- Can you delete Settings.vue altogether instead of moving it? It is a remnant from our starter code as well. You probably have to remove it from the Router too.

2020-12-15 22:45 UTC, hahnbeelee commented
> Thanks for doing this Hahnbee! I'm trusting Sam on this one so I do think we can merge it in, just make sure you mention that this happened in cp-dev after this gets finished. I also have a couple suggested changes haha.
> 
> * Can you move the 4 onboarding components and 1 scss file to their own separate folder as well?
> * Can you delete Settings.vue altogether instead of moving it? It is a remnant from our starter code as well. You probably have to remove it from the Router too.

Done!

2020-12-16 00:01 UTC, willespencer approved these changes
Looks good! Talked over slack but let's just wait till #159 is merged in to be extra safe!

2020-12-29 02:39 UTC, merged