4/n Accessibility - Heading structure
cornell-dti/course-plan pull request #365
Opened 2021-03-18 08:20 UTC by hahnbeelee

### Summary 
Added global headers to add meaningful sequence and a heading structure.
![image](https://user-images.githubusercontent.com/55263191/111592639-6b056e80-879f-11eb-8879-1f16887bb3f6.png)

### Test Plan 
- ensure there are no visual inconsistencies

### Notes
Things I found while doing this:
- [ ] Edit Semester modal needs to be refactored s.t. it follows the same format as all the other modals.

To-Do
- [ ] accessible dropdown component
- [ ] accessible + global button component
- [ ] onboarding needs to have its own set of headings
- [ ] aria tags
- [ ] more keyboard accessibility (should happen gradually)

2021-03-18 15:19 UTC, tcho6319 requested changes
Thanks Hahnbee! Left some nits and wanted to note an issue.

1. Since the `z-index: 2` for the `.navbar` in this feature PR's staging site (left), modals are covered by the nav bar. This seems to be resolved in master (right) because `z-index: 1`. However, this change also introduced a new bug as mentioned in https://github.com/cornell-dti/course-plan/pull/364#issuecomment-801962078 where the nav menu on mobile disappears. I've created a Notion bug item: [Funky z-index for Nav Bar (impact on mobile)](https://www.notion.so/courseplan/Funky-z-index-for-Nav-Bar-impact-on-mobile-b52786ee0ba44e68b1c1c8558023bdb9). This bug does not have to be resolved here and may be delegated to another dev but just wanted to lyk!
![Screen Shot 2021-03-18 at 11 04 57 AM](https://user-images.githubusercontent.com/54298311/111648488-c94f4300-87d9-11eb-9850-20e2c65ee9d3.png)

For the remaining TODO items you listed in your summary, would you like more help or do you think you can finish them this Sprint?

2021-03-18 15:19 UTC, tcho6319 commented on src/components/Modals/EditSemester.vue
> +    align-items: center;
I believe it should be `color: $sangBlue` and `border: 1px solid $sangBlue`. Is there a reason why the colors were changed?

This is an example of a modal design from Figma:
![Screen Shot 2021-03-18 at 11 02 11 AM](https://user-images.githubusercontent.com/54298311/111648061-665dac00-87d9-11eb-860c-2aedcf456dcf.png)

2021-03-18 15:49 UTC, hahnbeelee commented
> Thanks Hahnbee! Left some nits and wanted to note an issue.
> 
> 1. Since the `z-index: 2` for the `.navbar` in this feature PR's staging site (left), modals are covered by the nav bar. This seems to be resolved in master (right) because `z-index: 1`. However, this change also introduced a new bug as mentioned in [#364 (comment)](https://github.com/cornell-dti/course-plan/pull/364#issuecomment-801962078) where the nav menu on mobile disappears. I've created a Notion bug item: [Funky z-index for Nav Bar (impact on mobile)](https://www.notion.so/courseplan/Funky-z-index-for-Nav-Bar-impact-on-mobile-b52786ee0ba44e68b1c1c8558023bdb9). This bug does not have to be resolved here and may be delegated to another dev but just wanted to lyk!
>    ![Screen Shot 2021-03-18 at 11 04 57 AM](https://user-images.githubusercontent.com/54298311/111648488-c94f4300-87d9-11eb-9850-20e2c65ee9d3.png)
> 
> For the remaining TODO items you listed in your summary, would you like more help or do you think you can finish them this Sprint?

I have a plan for everything except the aria tags. If somebody has bandwidth and has time to do that that'd be great! But other than that I think my research + gained knowledge will make me the most suited to make those changes + most efficient.

2021-03-21 21:34 UTC, tcho6319 approved these changes
LGTM! Ty Hahnbee :)

2021-03-21 21:38 UTC, merged