[EZ} Update CS tech electives to be 3000+, not 3000 only
cornell-dti/course-plan pull request #369
Opened 2021-03-20 18:12 UTC by willespencer

### Summary 

Update the cs major technical electives checker to include courses that have a course number 3000 or above, and not just starting with a 3.

- [x] Updated cs checker
- [x] Ran req gen

![image](https://user-images.githubusercontent.com/25535093/111881310-415a6c00-8986-11eb-8e36-50c5ab11e6b4.png)

Remaining TODOs:

- [ ] This fixes the issue of courses 4000 level or above not being able to be applied properly to technical requirements, but does not fix the more complicated issue of 2000 or below courses that can be selected but should not be. This will be covered in the next sprint.

### Test Plan 

1. Confirm not only 3000 but 4000+ courses can be added to the technical req self check. Ensure that the course shows up under the requirement name and the counter increments.
2. Do the same for courses under 3000, and confirm the counter does not incremement.

2021-03-20 18:13 UTC, SamChou19815 approved these changes

2021-03-20 20:02 UTC, tcho6319 requested changes
Thanks Will! Works according to the updated checker but I pointed out how you'd want to handle an edge case. Once the comment is addressed, this PR should be g2g.

2021-03-20 20:13 UTC, willespencer commented on src/requirements/data/majors/cs.ts
> +        );
I could do that! I was originally considering that, but then I noticed the `Electives` requirement in the Info major checks 3000+ in this way. Should I change both to match your suggestion?

I also just noticed `CS Electives` seems to be the same as technical, in which it only checks 4000, but it should be 4000+. I'll also change it to match whatever I do for Technical and Info Electives!

2021-03-21 03:43 UTC, tcho6319 commented on src/requirements/data/majors/cs.ts
> +        );
I think by doing it the way I suggested, we would air on the side of allowing more courses (i.e. being more lenient with our checker) than accidentally leaving out certain levels.

2021-03-21 15:17 UTC, willespencer commented on src/requirements/data/majors/cs.ts
> +        );
Agreed! Just updated the code for CS technical electives, and applied the logic to CS 4000+ electives and INFO electives

2021-03-21 21:51 UTC, tcho6319 approved these changes
LGTM. Thanks Will! 

1. I see a similar issue on master as well so I don't think this issue is from any changes you made, but Technical Electives doesn't appear as a valid requirement when trying to add CS 7090 from the add modal. The assignment works when adding CS 7090 from the self check add modal. I will make a Notion item, but I wanted to lyk!

https://user-images.githubusercontent.com/54298311/111922000-fa47a600-8a6d-11eb-9ca0-4656e35585f9.mov

2021-03-21 22:28 UTC, merged