WIP 5/n - Divs to buttons (keyboard accessibility)
cornell-dti/course-plan pull request #381
Opened 2021-03-23 02:20 UTC by hahnbeelee

### Summary 
Changes all divs with a @click event to a button. This makes things much more keyboard accessible!

### Test Plan 
- make sure frontend hasn't changed
- press tab and make sure everything that should be clickable is highlighted

### Notes
This pretty much makes 99% of the site keyboard accessible. 
Other things left for keyboard accessibility:
- dropdown component
- modal refactor (if you open a model and use tab (things behind the modal get highlighted)

To-Do
- [x] change divs to buttons
- [x] more keyboard accessibility (should happen gradually)
- [ ] accessible dropdown component
- [ ] accessible + global button component
- [ ] onboarding needs to have its own set of headings
- [ ] aria tags
- [ ] Edit Semester modal needs to be refactored s.t. it follows the same format as all the other modals.

2021-03-23 13:52 UTC, SamChou19815 approved these changes
Everything seems to work.

> @SamChou19815 what are your thoughts on an eslint rule where if an element has a @click tag it has to be a button type?

That looks reasonable to me. Have you tried the eslint a11y plugin for vue?

2021-03-24 14:43 UTC, tcho6319 requested changes
Thank you so much Hahnbee! This looks great 🥰. I left a comment about a regression but once that's addressed, this PR should be g2g!

2021-03-24 14:43 UTC, tcho6319 commented on src/components/Semester/SemesterView.vue
> +        v-if="!isMobile"
I believe we brought back the ability to toggle between compact and not compact view in mobile so you can remove this line

2021-03-26 17:25 UTC, tcho6319 approved these changes
LGTM! Thanks Hahnbee :)

2021-03-27 05:25 UTC, merged