Generate only one full-courses.json
cornell-dti/course-plan pull request #458
Opened 2021-04-11 22:31 UTC by SamChou19815

### Summary 

Right now we have two set of course json: one in the functions folder of filtered courses, one in assets folder as `full-courses.json`. However, we only need one: `full-courses.json`, since we are already only using course data of the latest offerings.

This PR unifies the script to generate only one and removes the others. I updated all the usages to use the single source of truth.

### Test Plan 

`npm run req-gen`. It only generates small amount of changes, which shows that the change is good. (Small number of changes are expected, since cornell updates the roster regularly and new courses might be added in the semester.)

2021-04-13 13:07 UTC, tcho6319 requested changes
Thanks Sam! This code clean-up definitely makes the course fetching process simpler for other devs to follow. I requested some documentation but once that's addressed, this PR should be g2g.

2021-04-13 13:07 UTC, tcho6319 commented on src/requirements/courses-json-generator.ts
> +const getSemesters = async (): Promise<readonly string[]> => {
Can you document this code (like each `const` or at least in the form of a spec at the top of this script) to show that we're ultimately getting the latest offering of a course and then combining them into the full-courses.json?

2021-04-13 13:48 UTC, SamChou19815 commented on package.json
>      "courses-gen": "ts-node -T -P tsconfig.node.json src/requirements/courses-json-generator.ts",
Yes

2021-04-14 01:20 UTC, tcho6319 approved these changes
LGTM ty Sam!

2021-04-14 01:27 UTC, merged