Added Astronomy Major
cornell-dti/course-plan pull request #468
Opened 2021-04-18 23:21 UTC by jason-tung

### Summary 
Added ASTRO major
https://www.notion.so/courseplan/Add-the-Astronomy-STS-major-1d6c1972ba684cec8fc21d49e70f8b1c

![image](https://user-images.githubusercontent.com/33106747/115165311-412fb800-a07b-11eb-972f-e65e9551ea66.png)
![image](https://user-images.githubusercontent.com/33106747/115165285-278e7080-a07b-11eb-9205-2179e4a6e4c3.png)

### Test Plan 
Playtest on staging :~)

2021-04-19 02:31 UTC, hahnbeelee commented on src/requirements/data/majors/astro.ts
> +    MATH 1910, MATH 1120, or MATH 1220, MATH 1920, MATH 2220, or MATH 2240, and MATH 2930, MATH 4710, or ASTRO 3340`,
Nit - add periods to the ends of all of your descriptions

2021-04-19 02:34 UTC, hahnbeelee commented on src/requirements/data/majors/astro.ts
> +          'Two semesters of Advanced Astrophysics',
Change this to just 'Advanced Astrophysics' bc it looks verbose in the requirements bar
![image](https://user-images.githubusercontent.com/55263191/115173889-36cee780-a096-11eb-8df2-39a703a836b5.png)

2021-04-19 02:34 UTC, hahnbeelee commented on src/requirements/data/majors/astro.ts
> +          'Four semesters of physics',
change to 'Physics'

2021-04-19 02:35 UTC, hahnbeelee commented on src/requirements/data/majors/astro.ts
> +          'Two additional semesters of mathematics',
Mathematics Course

2021-04-19 02:37 UTC, hahnbeelee requested changes
left some comments on some string formatting, but other than that the general logic looks good :)

2021-04-22 23:51 UTC, tcho6319 approved these changes
LGTM! Thanks Jason. If @hahnbeelee's good with your updated changes as well, this PR should be g2g.

2021-04-27 15:02 UTC, hahnbeelee approved these changes
LGTM!

2021-04-27 21:18 UTC, merged