Set CUReviews data to N/A for new FA21 courses
cornell-dti/course-plan pull request #486
Opened 2021-05-01 22:13 UTC by willespencer

### Summary 

This pull request resolves the remaining issue in #485 - that the bottom bar could not be opened for new FA21 courses because there is no data for them yet on CUReviews.

![image](https://user-images.githubusercontent.com/25535093/116795887-29f2c080-aaa6-11eb-8fe9-4a7ed06f9121.png)

### Test Plan 

1. Ensure that clicking a new FA21 course like INFO 5101 or MUSIC 6270 opens up the bottom bar with "N/A" for each CUReviews field, and that the CUReviews link goes to their 404 page.
2. Ensure clicking a course with data such as CS 2110 still displays CUReviews data as expected, and switching tabs between that course and the new course still preserves the right data in the bottom bar.

### Notes 

Per the TPM of CUReviews, course data is usually added at the beginning of the semester (although they might do so soon because of a bug they are having), so this fix should be useful in future semesters as we add future semester data.

2021-05-01 22:17 UTC, SamChou19815 approved these changes

2021-05-02 03:21 UTC, tcho6319 requested changes
Thanks Will! There seems to be a styling discrepancy for the courses that don't exist on CU Reviews (e.g. INFO 5101). 


https://user-images.githubusercontent.com/54298311/116800963-b5cf1180-aad3-11eb-9cc4-473f5f09cbb9.mov

The bars for the three ratings should be wider as the screen width decreases. I compare INFO 5101 to DSOC 6110 (a course that exists on CU Reviews).

Once this discrepancy is resolved, this PR should be g2g!

2021-05-02 20:59 UTC, tcho6319 approved these changes
LGTM!

2021-05-02 22:42 UTC, tcho6319 approved these changes
LGTM!

2021-05-02 22:52 UTC, merged