Mpa Grad program
cornell-dti/course-plan pull request #513
Opened 2021-05-18 00:17 UTC by einc

### Summary 

Added the MPA grad program. 
@willespencer integrated the grad program with his front-end changes! 

### Test Plan 
Try adding the MPA grad program. Make sure that at least one undergrad or grad program is selected! 

### Notes 

- The concentration requirement for this program is self-check. I was trying to use toggleable requirements but because all of the concentrations are suggestions, I didn't think toggleable reqs really worked so I kept it self-check for now.
- Some of the grad requirements are Yes/No requirements (similar to the Swim Test) so we should add those next sem

2021-05-18 02:14 UTC, tcho6319 requested changes
Except for a few nits and a question about displaying the grad program name, this LGTM! @willespencer, I think Ein got to all the TODOs except the color one. Do you want to address that in her PR or wait for her to merge this one in before you make a new one?

Once my comments/questions are addressed, this PR should be g2g!

2021-05-18 02:14 UTC, tcho6319 commented on src/requirements/data/grad/mpa.ts
> +      'Three additional semester-length courses (or equivalent) in any of the three Foundation Areas',
Nit: period

2021-05-18 02:14 UTC, tcho6319 commented on src/requirements/data/grad/mpa.ts
> +      "Two courses to strengthen professional preparation, which may include statistical, analytical or mathematical skills, professional writing or speaking, leadership or management, or additional
Nit: missing period at the end of the last sentence

2021-05-18 02:14 UTC, tcho6319 commented on src/requirements/data/grad/mpa.ts
> +    description: 'PADM 5009, PADM 5011, and PADM 5012 (must be taken twice)',
Period

2021-05-18 02:14 UTC, tcho6319 commented on src/utilities.ts
> +  return grad ? grad.name : '';
The name of the grad program doesn't seem to show on req bar:
![Screen Shot 2021-05-17 at 9 56 30 PM](https://user-images.githubusercontent.com/54298311/118578761-bd8ce800-b75a-11eb-955b-48c042d5d073.png)

@einc is this intended behavior or do we want to show the name of the grad program?
In the case that we do want to show the name, I think you'll have to modify RequirementHeader.vue, @willespencer.

2021-05-18 21:40 UTC, einc commented
> Except for a few nits and a question about displaying the grad program name, this LGTM! @willespencer, I think Ein got to all the TODOs except the color one. Do you want to address that in her PR or wait for her to merge this one in before you make a new one?
> 
> Once my comments/questions are addressed, this PR should be g2g!

@willespencer did the TODOs on my laptop LOL so i could test the grad program <3 I added the colors one to Notion (for next sem) bc its a small, nice to have feature but not important functionality wise!

2021-05-19 21:27 UTC, tcho6319 approved these changes
LGTM! Test plan works. Thanks Will and Ein :D 

> The code to determine whether headers should display is quite complicated, and uses reqIndex and numOfColleges quite frequently. Left it mostly in-tact but added more to make sure grad programs work, but a refactor would make this code more simple and easy to change in the future.

@willespencer can you make a Notion item?

2021-05-19 21:27 UTC, tcho6319 commented on cypress/integration/test.spec.ts
> +  // TODO - breaking only on the CI, investigate
Can you make a Notion item for this if you haven't already?

2021-05-20 18:53 UTC, merged