Finish script to migrate engineering liberal studies data
cornell-dti/course-plan pull request #554
Opened 2021-10-22 21:20 UTC by SamChou19815

### Summary 

This PR finishes the script initially added in #542. The only real effective change is to add a more that actually modifies the database. I also tweaked some other logs produce by this script since I determined that they are all safe.

### Test Plan 

`npm run ts-node -- src/requirements/admin/migrate-engineering-liberal-arts-data.ts --run-on-db` if you want to run the script.

### Notes

I have local changes that removes the `allowDoubleCounting` flag. However, it can't be included in this PR, since removing the flag will break the assumption of the script that engineering liberal studies is double-countable.

We would need a coordinated release done in short time after this is merged. The sequence would be:

1. Release everything on master to prod before this PR is approved and merged.
2. Approve and merge this PR.
3. Run this on prod
4. PR for removing `allowDoubleCounting` is created, approved and merge to master.
5. (Optional) Another PR to delete this script
5. Create another release that contains the PR in step 4 only.

2021-11-02 20:23 UTC, hahnbeelee commented
Were you able to look into this concern from #542 ?

> In addition to the warning above, it also dies on some user on dev db that still has AS as their college while we only have AS1 and AS2 now. Not sure what's the story on prod data yet...

2021-11-02 20:53 UTC, SamChou19815 commented
> Were you able to look into this concern from #542 ?
> 
> 
> 
> > In addition to the warning above, it also dies on some user on dev db that still has AS as their college while we only have AS1 and AS2 now. Not sure what's the story on prod data yet...

@hahnbeelee 
There is no such problem on prod data so I just fixed the dev db data manually

2021-11-06 02:58 UTC, hahnbeelee commented
```

> vue-app@0.1.0 ts-node
> ts-node -T -P tsconfig.node.json "src/requirements/admin/migrate-engineering-liberal-arts-data.ts" "--run-on-db"

Running on abn53@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ac2677@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on acb352@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ag759@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ag946@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ag974@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ajc436@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on apb235@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ar699@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on atq2@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ay394@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on az354@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on bfs45@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on bsg68@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on bt277@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
    { courseId: 350898, uniqueId: 9, code: 'ARTH 3100', credits: 4 }
    { courseId: 350933, uniqueId: 24, code: 'ARTH 3650', credits: 4 }
    { courseId: 350996, uniqueId: 26, code: 'ARTH 4171', credits: 4 }
  [INFO] Somehow a requirement allow double counting is recorded as choice: College-EN-Engineering Distribution
  Now binding course with unique ID 9 (ARTH 3100) to College-EN-Liberal Studies: 6 courses.
  [INFO] Connected to Major-CS-Computer Science Core that can no longer be satisfied by course: 24.
  Now binding course with unique ID 24 (ARTH 3650) to College-EN-Liberal Studies: 6 courses.
  Now binding course with unique ID 26 (ARTH 4171) to College-EN-Liberal Studies: 6 courses.
  Relevant Choices Old:
  {}
  Choices Updates:
  {
    '9': 'College-EN-Liberal Studies: 6 courses',
    '24': 'College-EN-Liberal Studies: 6 courses',
    '26': 'College-EN-Liberal Studies: 6 courses'
  }
Running on bungaepyo@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cc2395@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cc736@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ceh279@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cf446@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ch746@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
    { courseId: 351993, uniqueId: 2, code: 'HD 3620', credits: 3 }
    { courseId: 365039, uniqueId: 0, code: 'EDUC 2610', credits: 3 }
    { courseId: 365928, uniqueId: 1, code: 'INFO 4240', credits: 3 }
    { courseId: 367429, uniqueId: 7, code: 'INFO 4430', credits: 3 }
  [INFO] Connected to College-EN-Mathematics that can no longer be satisfied by course: 2.
  Now binding course with unique ID 2 (HD 3620) to College-EN-Liberal Studies: 6 courses.
  Now binding course with unique ID 0 (EDUC 2610) to College-EN-Liberal Studies: 6 courses.
  [INFO] Connected to College-EN-Introduction to Engineering that can no longer be satisfied by course: 1.
  Now binding course with unique ID 1 (INFO 4240) to College-EN-Liberal Studies: 6 courses.
  Now binding course with unique ID 7 (INFO 4430) to College-EN-Liberal Studies: 6 courses.
  Relevant Choices Old:
  {}
  Choices Updates:
  {
    '0': 'College-EN-Liberal Studies: 6 courses',
    '1': 'College-EN-Liberal Studies: 6 courses',
    '2': 'College-EN-Liberal Studies: 6 courses',
    '7': 'College-EN-Liberal Studies: 6 courses'
  }
Running on cl2264@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cl859@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cll246@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on courseplan.cornelldti.test@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cph64@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cuterthanever.lee587@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on dtifluxtest@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ec592@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ec629@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
    { courseId: 350038, uniqueId: 81, code: 'ECON 1120', credits: 3 }
    { courseId: 350188, uniqueId: 82, code: 'ANTHR 1200', credits: 3 }
    { courseId: 350234, uniqueId: 83, code: 'ANTHR 1400', credits: 3 }
    { courseId: 350240, uniqueId: 84, code: 'NES 1312', credits: 3 }
    { courseId: 350262, uniqueId: 85, code: 'ASIAN 2208', credits: 3 }
    { courseId: 366630, uniqueId: 87, code: 'STS 1201', credits: 3 }
  [INFO] Course with unique ID 81 (ECON 1120) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 82 (ANTHR 1200) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 83 (ANTHR 1400) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 84 (NES 1312) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 85 (ASIAN 2208) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Somehow a requirement allow double counting is recorded as choice: College-EN-Engineering Communications
  Now binding course with unique ID 87 (STS 1201) to College-EN-Liberal Studies: 6 courses.
  Relevant Choices Old:
  {}
  Choices Updates:
  { '87': 'College-EN-Liberal Studies: 6 courses' }
Running on ein.chang@gmail.com...
  cours [...]

2021-11-06 03:09 UTC, hahnbeelee commented
Looks like for `jxh295@cornell.edu` their document in `user-selectable-requirements` didn't exist. I'm not sure when that would occur, but do we want to create a document for them, if we discover they don't exist?

2021-11-06 03:20 UTC, hahnbeelee requested changes
^ Just a request to address the comment above

2021-11-06 03:34 UTC, SamChou19815 commented
@hahnbeelee pushed a commit to fix that by using set. I think it should unblock running everything now.

2021-11-06 03:56 UTC, hahnbeelee commented
New output:
```

> vue-app@0.1.0 ts-node
> ts-node -T -P tsconfig.node.json "src/requirements/admin/migrate-engineering-liberal-arts-data.ts" "--run-on-db"

Running on abn53@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ac2677@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on acb352@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ag759@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ag946@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ag974@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ajc436@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on apb235@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ar699@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on atq2@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ay394@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on az354@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on bfs45@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on bsg68@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on bt277@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
    { courseId: 350898, uniqueId: 9, code: 'ARTH 3100', credits: 4 }
    { courseId: 350933, uniqueId: 24, code: 'ARTH 3650', credits: 4 }
    { courseId: 350996, uniqueId: 26, code: 'ARTH 4171', credits: 4 }
  [INFO] Course with unique ID 9 (ARTH 3100) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 24 (ARTH 3650) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 26 (ARTH 4171) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on bungaepyo@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cc2395@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cc736@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ceh279@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cf446@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ch746@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
    { courseId: 351993, uniqueId: 2, code: 'HD 3620', credits: 3 }
    { courseId: 365039, uniqueId: 0, code: 'EDUC 2610', credits: 3 }
    { courseId: 365928, uniqueId: 1, code: 'INFO 4240', credits: 3 }
    { courseId: 367429, uniqueId: 7, code: 'INFO 4430', credits: 3 }
  [INFO] Course with unique ID 2 (HD 3620) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 0 (EDUC 2610) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 1 (INFO 4240) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 7 (INFO 4430) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cl2264@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cl859@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cll246@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on courseplan.cornelldti.test@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cph64@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on cuterthanever.lee587@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on dtifluxtest@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ec592@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ec629@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
    { courseId: 350038, uniqueId: 81, code: 'ECON 1120', credits: 3 }
    { courseId: 350188, uniqueId: 82, code: 'ANTHR 1200', credits: 3 }
    { courseId: 350234, uniqueId: 83, code: 'ANTHR 1400', credits: 3 }
    { courseId: 350240, uniqueId: 84, code: 'NES 1312', credits: 3 }
    { courseId: 350262, uniqueId: 85, code: 'ASIAN 2208', credits: 3 }
    { courseId: 366630, uniqueId: 87, code: 'STS 1201', credits: 3 }
  [INFO] Course with unique ID 81 (ECON 1120) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 82 (ANTHR 1200) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 83 (ANTHR 1400) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 84 (NES 1312) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 85 (ASIAN 2208) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  [INFO] Course with unique ID 87 (STS 1201) is already bind to College-EN-Liberal Studies: 6 courses. Skip.
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on ein.chang@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on emilychn122@gmail.com...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
  Relevant Choices Old:
  {}
  Choices Updates:
  {}
Running on esh79@cornell.edu...
  coursesNotConnectedToOtherRequirementThatDoesNotAllowDoubleCounting
    { courseId: 351513, uniqueId: 10, code: 'PSYCH 2750', credits: 3 }
    { courseId: 359378, uniqueId: 7, code: 'INFO 2040', credits: 4 }
    { courseId: 360989, uniqueId: 8, code: 'INFO 2450', credits: 3 }
    { courseId: 361468, uniqueId: 5, code: 'INFO 4400', credits: 3 }
    { courseId: 365928, uniqueId: 2, code: 'INFO 4240', credits: 3 }
    { courseId: 365928, uniqueId: 3, code: 'INFO 4240', [...]

2021-11-06 03:56 UTC, hahnbeelee approved these changes
aight lgtm!

2021-11-06 16:54 UTC, SamChou19815 commented
@hahnbeelee I deleted some comments since they contain user emails.

2021-11-06 16:54 UTC, merged