Fix deployment of firebase functions to work for windows machines
cornell-dti/course-plan pull request #565
Opened 2021-11-02 03:07 UTC by willespencer

### Summary 

Fix deployment of firebase functions to work for windows machines, broken in #539 with the error `'..' is not recognized as an internal or external command,`

- [x] `npm install esbuild` in the firebase functions folder so it can be called without filepaths (see below notes for rationale)
- [x] Add `engines: node 10` to package to resolve the below error

![image](https://user-images.githubusercontent.com/25535093/139779845-1b52954a-8b77-49a0-ba46-5186442f4be0.png)

### Test Plan 

Confirm TrackUsers can be deployed to the dev env from the `functions` folder with `npm run deploy` and then successfully run and tested [here](https://console.cloud.google.com/functions/details/us-central1/TrackUsers?authuser=0&project=cornelldti-courseplan-dev&tab=testing) on both Windows and MacOS machines 

Windows:
![image](https://user-images.githubusercontent.com/25535093/139780103-7e2e0050-4786-4449-ac97-b0d085730a54.png)

Mac: Could @SamChou19815 or @hahnbeelee test this?

### Notes 

Notes on why the above changes were made instead of alternatives...

1. Trying to use the `cd` command to go into the existing directory with `esbuild` before calling it directly led to the deployment working, but the function failed to run on the cloud console - still not sure why.
2. Replacing the forward slashes with escaped back slashes worked locally, but doubt that this would work on Mac machines
3. Installing `esbuild` globally with `npm` worked as well, but this would require all other developers to do so or it would break on their machines.

2021-11-02 03:24 UTC, SamChou19815 approved these changes
LGTM

2021-11-04 02:34 UTC, hahnbeelee approved these changes
Ran `npm run deploy` on the dev instance and ran trackUsers [here](https://console.cloud.google.com/functions/details/us-central1/TrackUsers?project=cornelldti-courseplan-dev&tab=testing) Works well for me!

2021-11-04 02:37 UTC, hahnbeelee requested changes
waitttt when I try to run it locally this happens:
![image](https://user-images.githubusercontent.com/55263191/140248391-d1c84c34-94f6-47d3-b56a-da96013ff044.png)

2021-11-04 02:56 UTC, SamChou19815 commented
> waitttt when I try to run it locally this happens: ![image](https://user-images.githubusercontent.com/55263191/140248391-d1c84c34-94f6-47d3-b56a-da96013ff044.png)

This is also pre-existing on master, and it's caused by my bundling change. So i think it's better to let this one go through first and we can think how to deal with that later.

On that note, I'm not sure what's the benefit of keeping this as a firebase function instead of a normal script, so maybe we don't need to solve that problem after all...

2021-11-04 22:59 UTC, hahnbeelee approved these changes
Ok per Sam's last comment - let's push! :)

2021-11-07 00:01 UTC, merged