Requirement builder with the new data format
cornell-dti/course-plan pull request #588
Opened 2021-11-14 23:06 UTC by SamChou19815

### Summary 

Depends on #587.

This PR switches the requirement building algorithm to use the new data format proposed in #522. It only builds the first graph (the graph that keeps all the edges with constraint violations) for now, since the current data enforces that there are no constraint violations. 

### Test Plan 

Load it the first time and compare your requirement progress against staging. It should be mostly the same. There might be some discrepancies with edges from requirement with warnings to AP/IB credits, since the new implementation fixes the bug in the old system (See https://github.com/cornell-dti/course-plan/pull/553#discussion_r734788977 when I first write the migration script).

<img width="2560" alt="Screen Shot 2021-11-14 at 17 54 59" src="https://user-images.githubusercontent.com/4290500/141702156-748fb40a-d867-4e83-8d5c-113e945a3a3a.png">

After that, you can play around with adding courses and requirements from both the semester view and the requirement bar, with both regular and self-check requirements. Everything should work fine.

I would like to get more eyes on this since it's a pretty significant change.

2021-11-30 17:14 UTC, hahnbeelee commented
When I dragged CS 4121 for the CS Practicum requirement it fulfilled both the CS Elective and CS Practicum requirement. This doesn't happen on prod.
![image](https://user-images.githubusercontent.com/55263191/144094898-b267d2c9-556a-44ef-b884-d61ebe74df24.png)

2021-11-30 17:20 UTC, hahnbeelee commented
When I added a course from the add modal from the req bar for tech elec it got counted as tech elec and cs elec
![image](https://user-images.githubusercontent.com/55263191/144095913-90c23516-3c2f-47ab-9456-7ac518d6629f.png)

![image](https://user-images.githubusercontent.com/55263191/144095870-a8701b64-13e1-4881-8482-ed5607a74806.png)

2021-11-30 17:25 UTC, hahnbeelee commented
Weird bug where I added CS 3300 as an external spec from the req bar, but it didn't actually get added? The course card isn't in the semester view, and it isn't being counted for actually fulfilling the requirement (0/3)
![image](https://user-images.githubusercontent.com/55263191/144096591-886712a0-2d88-4307-b56f-1138b66f9d40.png)

2021-11-30 18:33 UTC, hahnbeelee commented
Fulfilled course cards are not showing for self-select (specifically the CS major tech elec) - notice 2/3 but no courses listed
![image](https://user-images.githubusercontent.com/55263191/144106837-c127087b-1231-4ef1-a4be-1259183ab52b.png)

2021-11-30 18:37 UTC, hahnbeelee commented
local vs. prod.
![image](https://user-images.githubusercontent.com/55263191/144107367-98947b44-ab1a-4aba-8616-4261de37407f.png)
![image](https://user-images.githubusercontent.com/55263191/144107384-cccd7a46-875b-4eff-93f6-849568952f9a.png)

2021-11-30 18:37 UTC, hahnbeelee requested changes
I see the change of AP/IB not fulfilling requirements by default.
Tested + Works as desired:
Delete a course
add a course 
add semester
clear semester
delete a semester

Weird behavior with:
- selectable requirements

2021-11-30 20:53 UTC, SamChou19815 commented on src/global-firestore-data/semesters.ts
> +  choiceUpdater: (choice: FirestoreCourseOptInOptOutChoices) => FirestoreCourseOptInOptOutChoices,
It's a function that takes in the current choice as parameter and return the updated choice.

2021-11-30 20:53 UTC, SamChou19815 commented
@hahnbeelee all the above-mentioned issues should be fixed now. How I fixed them is explain in the commit message.

2021-12-02 01:53 UTC, hahnbeelee requested changes
Thank you! I found something else - when I add CS 4210 the modal says it's mapping to "CS Electives" but when I added it it automatically fulfilled all the requirements it could possibly fulfill. LOL
![image](https://user-images.githubusercontent.com/55263191/144342455-a02dd14d-8937-4ca2-904e-f857069630a2.png)

2021-12-02 04:11 UTC, SamChou19815 commented
> Thank you! I found something else - when I add CS 4210 the modal says it's mapping to "CS Electives" but when I added it it automatically fulfilled all the requirements it could possibly fulfill. LOL ![image](https://user-images.githubusercontent.com/55263191/144342455-a02dd14d-8937-4ca2-904e-f857069630a2.png)

Should be fixed in the last commit. Turns out a filter condition is inverted 😅

2021-12-03 07:58 UTC, hahnbeelee requested changes
I think this is my last round of comments.

2021-12-03 16:22 UTC, SamChou19815 commented on src/requirements/requirement-frontend-utils.ts
> -          !(optOutSlotNames && (fulfilledBy === 'credits' || optOutSlotNames.has(slotName)))
Yep, I don't think we need this. The new requirement flow will never opt-out of a single slot, but instead the entire requirement.

2021-12-03 17:00 UTC, SamChou19815 commented on src/requirements/admin/requirement-graph-admin-utils.ts
> -  selectableRequirementChoicesCollection,
All migrated away

2021-12-03 22:41 UTC, hahnbeelee approved these changes
LGTM!

2021-12-04 00:19 UTC, merged