Refactor constraint violations
cornell-dti/course-plan pull request #633
Opened 2022-01-08 02:40 UTC by benjamin-shen

### Summary 

This pull request starts to implement constraint violations in a more generalized way.

- [x] refactored constraint violations from `removeIllegalEdgesFromRequirementFulfillmentGraph()`
- [x] modified `getAllEligibleRelatedRequirementIds()` to only opt out of requirements in constraint violations
- [x] fixed #626's requirements bug

Remaining TODOs:

- [ ] change graph requirement type from `string` to `RequirementWithIDSourceType`
- [ ] add other kinds of constraint violations (we might want to discuss what these are)
- [ ] fix allowDoubleCounting() function to account for major/minor/grad

### Test Plan 

No frontend changes except fixing the dragged course requirements bug. Steps:
1. Choose Engineering college and CS major
2. Drag MATH 4710, under the Chemistry / CHEM 2080 college requirement, to a semester
3. Make sure that the course fulfills the Probability major requirement

2022-01-15 20:11 UTC, willespencer requested changes
Left a bunch of comments! Your explanation really helped get through this and very excited for these changes 😄 

Also tested some things detailed below

1. I checked how double counting affects minors (specifically the Human Development minor).

A big improvement is how the double counting issue is fixed for minors - so now since the two requirements do not have the double counting flag, courses from the add modal must select only one - unlike on CoursePlan where one course can fulfill both reqs.
![image](https://user-images.githubusercontent.com/25535093/149636219-1e79801b-36d0-40f6-8d70-55b2bbdb9586.png)

However, when added from the add modal, for some reason this course cannot be applied to both `Liberal Studies` and the minor unlike prod even though this should be allowed I believe. Can this be fixed before the new add modal?
![image](https://user-images.githubusercontent.com/25535093/149636265-50f61b08-9c22-4fdf-b7b6-d0a809e365fb.png)

2. Requirements/Double counting seems to work as expected in other cases! For example, `CS 1110` fulfills the computing requirement in Eng and CS simultaneously, `CS 4850` fulfills two reqs in CS, and a class like `ECON 3040` can be applied to MPA or Engineering, but not both.

2022-01-15 20:27 UTC, benjamin-shen commented on src/requirements/requirement-frontend-computation.ts
> +  readonly requirementsThatDoNotAllowDoubleCounting: Map<string | number, Set<string[]>>;
The mapping is from course unique id (`string | number`) to requirement id (`string`).

>mapping a requirement to a set of requirements that cannot be double counted with it

This is an intermediary step in `getConstraintViolationsForSingleCourse()` to generate `requirementsThatDoNotAllowDoubleCounting`, the variable name is `constraintViolatingRequirements`.

Should I rename the variable(s)?

2022-01-15 20:28 UTC, benjamin-shen commented on src/requirements/requirement-frontend-computation.ts
> +    userRequirementsMap,
`userRequirementsMap` is computed the same way and returned in `buildRequirementFulfillmentGraphFromUserData()`, so I'm just removing repeated code.

2022-01-15 20:31 UTC, benjamin-shen commented on src/requirements/requirement-frontend-utils.ts
> +    requirementA.allowCourseDoubleCounting || requirementB.allowCourseDoubleCounting || false;
The `allowCourseDoubleCounting` property can be undefined.

2022-01-15 20:38 UTC, benjamin-shen commented on src/requirements/requirement-frontend-utils.ts
> +    return true;
afaict, minors are specifically for undergrads.
![image](https://user-images.githubusercontent.com/34158284/149636955-844dd49d-c486-4d37-8b9d-49ded004c4be.png)

I'm not sure how a major+minor+grad combination would work. I'm thinking you shouldn't be able to double count a course for a minor requirement and a grad requirement, but I could be wrong. @einc do you know?

2022-01-15 20:41 UTC, benjamin-shen commented on src/requirements/requirement-frontend-utils.ts
> +  // uniqueId: number,
ok 😢

2022-01-15 20:42 UTC, benjamin-shen commented on src/requirements/requirement-frontend-utils.ts
> +  // TODO @bshen fix this
yeah, i'll delete it in this PR

2022-01-15 20:42 UTC, benjamin-shen commented on src/requirements/requirement-constraints-utils.ts
> +  a.size === b.size && [...a].every(value => b.has(value));
[shameless](https://stackoverflow.com/a/44827922)

2022-01-15 20:44 UTC, benjamin-shen commented on src/requirements/requirement-constraints-utils.ts
> +const setAdd = <T>(set: Set<T>, value: T) => {
I don't think it's necessary for now, but maybe we should if we find ourselves needing to refactor & use them in other places as well

2022-01-15 21:59 UTC, willespencer commented on src/requirements/requirement-frontend-computation.ts
> +  readonly requirementsThatDoNotAllowDoubleCounting: Map<string | number, Set<string[]>>;
Could you rename the former to something like `requirementsThatDoNotAllowDoubleCountingForCourses` to match the name of `requirementsThatDoNotAllowDoubleCountingForSingleCourse` ?

2022-01-15 22:18 UTC, benjamin-shen commented on src/requirements/requirement-constraints-utils.ts
> +  requirementsThatDoNotAllowDoubleCounting: Map<string | number, Set<Requirement[]>>;
It basically means the same thing. Where you see `string` is usually in places where the function is called / the value is returned (and generics aren't used).

2022-01-17 01:54 UTC, einc commented on src/requirements/requirement-frontend-utils.ts
> +    return true;
[Yup](https://www.cornell.edu/academics/fields.cfm) just for UG. 
It seems like [graduate minors](https://gradschool.cornell.edu/academics/fields-of-study/field/sustainable-energy-minor/) also exist, but I don't think we need to worry about these for now.

2022-01-17 05:00 UTC, willespencer approved these changes
All changes LGTM!

2022-01-18 02:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cornell-dti/course-plan?pullRequest=633) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cornell-dti/course-plan?pullRequest=633) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cornell-dti/course-plan?pullRequest=633) it.</sub>

2022-01-18 03:38 UTC, merged