Add progress tracker toolcard
cornell-dti/course-plan pull request #722
Opened 2022-10-17 22:46 UTC by jerrry1123

### Summary 
- Added a new toolcard in the tools section showing progress for college, major, minor, and grad school requirements
- 

This pull request is the first step towards finishing the tools page.

Remaining TODOs:

- Find any outstandings bugs with the progress toolcard

### Test Plan 

- Test that the progress bar moves according to the number of requirements fulfilled 
- Test that the text changes correctly with the number of requirements fulfilled and choice of major, minor, college, etc.
- Test that the text does not show up when a minor or grad school were not chosen

2022-10-17 23:00 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +        }
```suggestion
        switch (req.groupName) {
          case 'College':
          case 'Major':
          case 'Minor':
          case 'Grad':
            this.hasGrad = true;
            this.gradRequirementCount.finished = totalCompleted;
            this.gradRequirementCount.needed = totalRequired;
        }
```

2022-10-17 23:00 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    progressValue(): String {
```suggestion
    progressValue(): string {
```

2022-10-17 23:00 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +      let progress = this.sumRequirements;
What is this for?

2022-10-17 23:00 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    margin-bottom: 4px;
No pixels pls

2022-10-17 23:00 UTC, zachary0kent commented on src/containers/Tools.vue
>        <!--      </card>-->
Can you delete commented code?

2022-10-17 23:00 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +          if (!(req.fulfillment.fulfilledBy === 'self-check')) {
```suggestion
          if (req.fulfillment.fulfilledBy !== 'self-check') {
```

2022-10-17 23:03 UTC, zachary0kent requested changes
I think the logic for selecting the emoji is a little buggy

2022-10-17 23:03 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +      }
I think the following `if`s need to be `else if`s--it'll always return the fire emoji if `progress < 0.8`.

2022-10-18 05:42 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    progressValue(): string {
Is this used anywhere?

2022-10-18 05:42 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    getTransform(): string {
Same with this--seems like it's unsused

2022-10-18 05:43 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    getProgressString(): string {
This doesn't have to be a function--you can attach the message directly to the component

2022-10-18 05:55 UTC, zachary0kent reviewed
Great job on the toolcard--it looks great! I think you might have created the branch from `fixProfilePageIssues` though.

2022-10-18 05:55 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +        }
```suggestion
        this.gradRequirementCount.finished = totalCompleted;
        this.gradRequirementCount.needed = totalRequired;
        switch (r.groupName) {
          case 'College':
            this.hasCollege = true;
            break;
          case 'Major':
            this.hasMajor = true;
            break;
          case 'Minor':
            this.hasMinor = true;
            break;
          default:
            this.hasGrad = true;
            break;
        }
```

2022-10-18 05:55 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +      },
These are constants right? I think this can be removed if you make the change I suggested below.

2022-10-18 05:55 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +        }
Also can we replace the default case with `'Grad'`?

2022-10-18 05:55 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +      return this.progressImg.Confetti;
```suggestion
      if (progress < 0.2) {
        return hands;
      }
      if (progress < 0.4) {
        return flex;
      }
      if (progress < 0.6) {
        return star;
      }
      if (progress < 0.8) {
        return fire;
      }
      return confetti;
```

2022-10-18 06:39 UTC, noschiff commented
<img width="535" alt="image" src="https://user-images.githubusercontent.com/47431797/196354404-8f3093f5-1cc9-4cef-a0f0-e2a1624c13e3.png">
we should probably handle decimals a little cleaner

2022-10-23 16:14 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    line-height: 1rem;
These conflict with each other

2022-10-23 16:14 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    font-weight: 400;
Can you use `font` shorthand?

2022-10-23 16:14 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    line-height: 0.938rem;
Only use either `font-size` or `line-height`. No need to set both.

2022-10-23 16:14 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    font-style: normal;
Can you use `font` shorthand property

2022-10-23 16:17 UTC, zachary0kent commented on src/components/Tools/ProgressTracker.vue
> +    margin-bottom: 0.25rem;
The `margin` and `margin-bottom` properties conflict

2022-10-25 01:25 UTC, zachary0kent requested changes
<img width="641" alt="Screen Shot 2022-10-24 at 9 25 08 PM" src="https://user-images.githubusercontent.com/73757337/197660312-11f33bae-98d0-47ce-ab2d-4a46262b865c.png">
Looks to be a bit off center. I also think we should floor the number of requirements completed to an integer.

2022-10-25 02:59 UTC, noschiff requested changes
First, I think we might be a little optimistic to say "You are almost there!" when the user has barely completed any requirements.

Second, how have I completed 2 college requirements? Is it that multiple incomplete requirements are being added together to get to 2 completed? First, I'd be curious to hear what designers think since there's definitely some pros and cons to it. ~~Second, I don't even think this is adding partial completions together since I don't see how this could equal 2.~~ Hmm... I think the 2 reqs was a bug with the req sidebar. But still, I don't love adding partials together.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/47431797/197670863-9d5723ed-f1d5-4f4d-8a1a-61189d7f693a.png">
<img width="397" alt="image" src="https://user-images.githubusercontent.com/47431797/197671449-0e8a84ba-a7f0-49c4-98bd-2611dc003f11.png">

My requirements graph is:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/47431797/197671403-f344bf41-d492-4782-9889-81859388c5eb.png">

2022-10-26 03:05 UTC, noschiff commented
Why did we move away from the design (shown below) for the righthand side of the tool card? Is this design out of date? I think it looks better to show what the user has left to do as opposed to a fraction.

<img alt="image" src="https://user-images.githubusercontent.com/47431797/197924854-61366573-6ff5-4053-bacf-ad03e65032bf.png">

2022-10-27 22:23 UTC, noschiff commented
I'd really prefer to reuse the functions in RequirementsHeader rather than trying to rework everything again. Redoing it will make it impossible to handle dangerous stuff in the future. (discussed w @zachary0kent offline)

2022-10-27 23:47 UTC, noschiff commented
**This branch is terminated. We have pivoted to [progress-tracker](https://github.com/cornell-dti/course-plan/tree/zak/progress-tracker).**

2022-10-27 23:47 UTC, closed without merging