Multiple plans dropdown
cornell-dti/course-plan pull request #806
Opened 2023-03-26 02:54 UTC by elizabeth-tang

### Summary 

- Implemented frontend for multiple plans dropdown
- Created cypress tests for open/close states

### Test Plan 

- Is dropdown initially closed?
- Does it open when clicked. Does it close when clicked again? Does arrow flip? 
- Does "No additional plans" show when only one plan is in the data?
- Does current plan text change when another plan is clicked?

2023-03-27 00:19 UTC, mirandayu131 requested changes
Can you include in your test plan how to enable the feature flag so I can see your changes?

2023-03-27 01:57 UTC, zachary0kent requested changes
<img width="1440" alt="Screenshot 2023-03-26 at 9 56 46 PM" src="https://user-images.githubusercontent.com/73757337/227822597-ff23721d-f8f2-4331-96fe-cb7c56cad4c7.png">
Looks good overall! I just encountered one issue when shrinking the size of the screen; it seems the padding between the arrow and the right side of the dropdown changes as you adjust the screen size.

2023-03-27 01:57 UTC, zachary0kent commented on cypress/integration/test.spec.ts
> +  cy.get('[data-cyId=multiplePlans-wrapper]').should('not.have.class', 'shown');
Would `.should('be.visible')` work here instead?

2023-03-27 01:57 UTC, zachary0kent commented on package.json
> +    "cypress": "^6.9.1",
Any reason we bumped cypress?

2023-03-27 01:57 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +          v-for="plan in filterPlans"
Can you rename the `plan` identifier used in the `v-for`?

2023-03-27 01:57 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +      const filtered = this.$data.plans.filter(plan => plan !== this.$data.currplan);
```suggestion
      const filtered = this.plans.filter(plan => plan !== this.currplan);
```

2023-03-27 01:57 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +      editplan,
Can we use camelCase?

2023-03-27 01:57 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +        <div class="multiplePlans-dropdown-placeholder up-arrow" v-if="shown"></div>
```suggestion
        <div class="multiplePlans-dropdown-placeholder up-arrow" v-if="shown"></div>
        <div class="multiplePlans-dropdown-placeholder down-arrow" v-else></div>
```

2023-03-27 01:57 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +    filterPlans() {
Can you rename this to something more descriptive like `otherPlans` or `deselectedPlans`?

2023-03-27 01:57 UTC, zachary0kent commented on src/components/Requirements/RequirementSideBar.vue
> +              <multiple-plans-dropdown></multiple-plans-dropdown>
```suggestion
              <multiple-plans-dropdown />
```

2023-03-27 02:39 UTC, zachary0kent reviewed
Also, can we avoid use of pixels? I see you're using rem in some places, which is good.

2023-03-27 02:39 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +    color: #636363;
Can we either use a similar color from `src/assets/constants/colors` or add this there if need be?

2023-03-27 02:39 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +      background-color: #ffffff;
```suggestion
      background-color: white;
```

2023-03-27 02:39 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +      color: #858585;
Same comment about this color

2023-03-27 02:39 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +      font-weight: normal;
What happens if these properties aren't set?

2023-03-27 02:42 UTC, zachary0kent commented on src/components/Requirements/MultiplePlansDropdown.vue
> +        <div class="multiplePlans-dropdown-placeholder down-arrow" v-else></div>
Is there a reason you didn't use `img` tags for the arrow?

2023-03-28 20:07 UTC, zachary0kent requested changes
<img width="1440" alt="Screenshot 2023-03-28 at 4 06 29 PM" src="https://user-images.githubusercontent.com/73757337/228354585-03c38faf-ad70-4cb4-89ab-4433c21af04f.png">
Can you add a hover state for hovering over a different plan? Also, can you add more plans just to make sure they align correctly in the dropdown?

2023-03-29 00:57 UTC, zachary0kent approved these changes
Looks good to me!

2023-03-29 17:39 UTC, zachary0kent requested changes
Actually, sorry for one last request, but if you copied the styling from another dropdown, can you factor the CSS into an SCSS file?

2023-03-30 20:04 UTC, zachary0kent commented
Thanks for factoring out the styling! Can you import the stylesheet from where you had copied the styling?

2023-03-31 02:26 UTC, zachary0kent approved these changes
Looks great, thanks for the hard work!

2023-04-12 00:04 UTC, mirandayu131 approved these changes
Looks good to me :)

2023-04-16 17:37 UTC, merged