Modify Liberal Studies Checker
cornell-dti/course-plan pull request #818
Opened 2023-04-21 01:05 UTC by mirandayu131

Modifies the checker for the liberal studies requirement to check whether the given course’s `crseId` is in the other yes list JSON. Additionally, it checks whether `distribution` is included in the categories listed under the other yes list for the given course. Currently, we determine whether it is classified under category `distribution` by checking if `course.catalogDistr?.includes(distribution)` is True.

Test Plan
- Test whether other Yes List Courses from https://apps.engineering.cornell.edu/liberalstudies/ApprovedLiberalStudies.pdf satisfy the Liberal Studies requirement on the server

2023-04-21 14:26 UTC, zachary0kent reviewed
Awesome work, everything behaves as expected! I'll approve once all the previous liberal studies PRs are merged :)

2023-04-21 17:48 UTC, noschiff commented
Amazing work, Miranda! Super excited to release this! 🚀

2023-04-30 15:14 UTC, zachary0kent requested changes

2023-04-30 15:14 UTC, zachary0kent commented on src/requirements/checkers.ts
> +  // console.log(otherYesCourse?.categories?.includes(distribution));
```suggestion
```

2023-04-30 15:14 UTC, zachary0kent commented on src/requirements/checkers.ts
> +    otherYesCourse?.categories?.includes(distribution)
Is the optional chaining after `categories` necessary--will the property `categories` every be absent on `otherYesCourse`, if it exists?

2023-05-03 00:24 UTC, zachary0kent approved these changes
Looks good!

2023-05-03 00:24 UTC, merged