Adding nutrition major
cornell-dti/course-plan pull request #867
Opened 2023-10-23 02:16 UTC by nidhi-mylavarapu

### Added Nutrition Sciences Major in CALS!

This PR is to add the Nutritional Sciences major to CP! 

### Test Plan 

- Double check major/course requirements with Cornell Registrar
- Add some courses and make sure updates appear appropriately in the left sidebar (test more complicated/important requirements if possible - specifically Advanced Electives, Nutrition Core)

2023-10-23 21:00 UTC, zachary-kent reviewed
It looks like there are some merge conflicts resulting from me adding importing new courses; you can resolve these by merging main into your branch, accepting all incoming changes, and then re-running `npm run req-gen`.

2023-10-31 02:21 UTC, zachary-kent requested changes
Great work! Just a couple minor nits :)

2023-10-31 02:21 UTC, zachary-kent commented on src/data/majors/ns.ts
> +    checker: includesWithSubRequirements(['CHEM 2510', 'CHEM 3010']),
```suggestion
    checker: includesWithSingleRequirement('CHEM 2510', 'CHEM 3010'),
```
We have a special function for where there is only one slot--can you make this change throughout this file?

2023-10-31 02:21 UTC, zachary-kent commented on src/data/majors/ns.ts
> +              distribution => hasCategory(course, distribution) ?? false
Why do we need `?? false`?

2024-03-20 22:39 UTC, andxu282 approved these changes

2024-03-20 22:39 UTC, andxu282 approved these changes

2024-04-14 14:10 UTC, merged