[Schedule Generator] Schedule Fixes
cornell-dti/course-plan pull request #913
Opened 2024-03-25 22:01 UTC by andxu282

### Summary 
Fixes a couple of frontend issues for the schedule component
- [x] the Courses and Schedules sections now use `display: flex` so they're always aligned
- [x] course heights are always fixed and the schedule component height is calculated based on the number of hours, so overflow will never occur.

https://github.com/cornell-dti/course-plan/assets/53061040/a3466cbd-4016-4db9-9c9c-6a1987a16b03

https://github.com/cornell-dti/course-plan/assets/53061040/88f3f2c3-0c62-4afe-8298-535be7bd7585

2024-04-13 21:17 UTC, plumshum reviewed
The fixes overall look good to me. 
Your comment about what would happen if there are too many courses and it overflows, I think we should make the `Your Courses` component scrollable then. The height and width of the component shouldn't change.  
Seems like there are a few css colors that we can convert into scss variables aswell. (Line 178 in `Schedule.vue`.)

2024-04-14 23:17 UTC, elizabeth-gs requested changes
Looks really good! Just a few small nits:

- can we extend the lines and the times to fill the space? I've had classes late at night before (i.e. 7:30-8:45). If that exceeds the bounds of the modal, I think we should also make the component scrollable.

2024-04-14 23:17 UTC, elizabeth-gs commented on src/components/ScheduleGenerate/Schedule.vue
> +    border-left: 1px solid #e5e5e5;
can we extract this into a color variable?

2024-04-14 23:17 UTC, elizabeth-gs commented on src/components/ScheduleGenerate/ScheduleGenerateModal.vue
> +              Fall 2024
This should probably be a prop (selectedSemester), like you have for `ScheduleGenerateSideBar.vue` that you pass in from `Dashboard.vue`.

2024-04-18 18:34 UTC, merged