add collection into firesbase
cornell-dti/course-plan pull request #921
Opened 2024-04-24 01:33 UTC by plumshum

### Summary 

This pull request is the first step towards adding collection into Firebase for implementing the Save Courses Feature.

- [x] add collection to firebase
- [ ]Add firebase function to modify (add, delete, edit) from collections
- Stub functions into frontend components

Remaining TODOs:

Depends on #{number of PR}
need to make sure it works with #912 

### Test Plan 

### Notes 

### Blockers 

- A newly discovered dependency that hasn’t been addressed

### Breaking Changes  

- Database schema change (anything that changes Firestore collection structure)
- Other change that could cause problems (Detailed in notes)

2024-05-02 01:00 UTC, Destaq reviewed
Great work Hannah! And I appreciate that this is still a quasi-draft PR (make sure that you open things appropriately in the future when not fully ready for review), so makes sense that there are some of the `console.log`s and `TODO`s. Just please ensure that these are all removed when all the other commits are finished, for the reasons I outlined.

In general, looks fantastic and you did a really good job with TypeScript too. Good to have a chance to start working with Vuex, that's very critical to the web app. In terms of future work, would just encourage you to do some minor refactoring (maybe not now, but at least before the merge request proper) and test that the Firebase writing works. Whenever you need any help finishing stuff up feel free to message or find me.

Also, if it would be possible to update the description for this PR that would be great, I think you may have left some parts of the initial boilerplate intact.

2024-05-05 17:35 UTC, elizabeth-tang requested changes
Awesome, it's really coming along Hannah!! I know some of the stuff Simon mentioned are present in the existing codebase so it's ok to leave to later to address. Thanks for working on this!

2024-05-05 17:35 UTC, elizabeth-tang commented on src/global-firestore-data/user-semesters.ts
> +  await updateDoc(doc(semestersCollection, store.state.currentFirebaseUser.email), {
Should be ok for now -- the semestersCollection already allows for read and write

2024-05-05 17:35 UTC, elizabeth-tang commented on src/global-firestore-data/user-semesters.ts
> +  store.commit('setOrderByNewest', store.state.orderByNewest);
This shouldn't be necessary here since editing collections should not change the ordering of the semesters

2024-05-05 17:35 UTC, elizabeth-tang commented on src/global-firestore-data/user-semesters.ts
> +  name: string,
I think it's ok for codebase consistency -- we initialize most of our objects (semester, plan, etc) like that

2024-10-05 21:22 UTC, closed without merging