WIP: implement duplicate schedule checking in schedule generator
cornell-dti/course-plan pull request #974
Opened 2024-12-10 22:34 UTC by import-brain

### Summary 

This is a WIP PR implementing duplicate checking for schedules in the CoursePlan schedule generator.

Problems, todos, and future considerations:

- [ ] Course time slots are not correct for Spring '25
- [ ] Need to add discussion/lab times
- [ ] Need a better algorithm than the current randomization one— my current approach with manually timing out the generation after 1 second isn't very optimal
- [ ] Update pagination bounds when number of possible schedules is less than 5

2025-02-04 00:01 UTC, ejcheng commented
https://www.npmjs.com/package/object-hash

2025-02-10 03:57 UTC, plumshum commented on src/components/ScheduleGenerate/ScheduleGenerateModal.vue
> +import _ from 'lodash';
should move this line between line 120 and 121.

2025-02-10 03:57 UTC, plumshum commented on src/components/ScheduleGenerate/ScheduleGenerateModal.vue
> +        const secondScheduleEntries = Array.from(first.schedule.entries());
I believe there's a slight bug. It should be ` const secondScheduleEntries = Array.from(first.schedule.entries());` , or else you're just comparing the same entries from `first`, then this function always returns True. Let me know if that's not the case though!

2025-02-10 03:58 UTC, plumshum commented on src/components/ScheduleGenerate/ScheduleGenerateModal.vue
> +        const secondScheduleEntries = Array.from(first.schedule.entries());
Can also add a length check to return `false` early aswell.

2025-02-10 04:00 UTC, plumshum requested changes
Hi Eric. I left a few comments for this PR. I believe there is a slight bug for `isEqual`. Also, I think we should discuss how many pages we want the scheduler generator to output, because if we have more than 10+ pages, that might be too much for the user. But I also agree that we shouldn't always produce 5 pages. Good job!

2025-04-14 02:08 UTC, plumshum approved these changes

2025-04-14 02:08 UTC, plumshum commented on src/components/ScheduleGenerate/ScheduleGenerateModal.vue
> +        return true;
Great job with the bug fix for the first and second course. makes sense that we have to check equality between the schedules' length, the course timeslots' length, and the time-slot values themselves.

2025-04-14 02:09 UTC, plumshum commented on src/components/ScheduleGenerate/ScheduleGenerateModal.vue
> +        return true;
also to make this merge work you should change the artifact version to pass the front-end tests

2025-04-15 05:03 UTC, ejcheng commented on src/components/ScheduleGenerate/ScheduleGenerateModal.vue
> +        return true;
Thanks!

2025-04-15 05:10 UTC, merged